Squeeze identical lines
sharkdp/hexyl pull request #213
Opened 2023-12-12 17:30 UTC by sharifhsn

Fixes #186.

This brings the squeezing feature to parity with `hexdump`. Lines that contain identical data should be squeezed, not just when they are all filled with a single byte.

2023-12-12 18:30 UTC, sharkdp commented
Thank you very much!

Some tests are currently failing..

2023-12-12 18:36 UTC, sharifhsn commented
Looks like the issues are on 32-bit systems. I'll investigate.

2024-09-08 11:12 UTC, sharkdp commented
Note: there is also #218

2024-09-08 12:05 UTC, GrigorenkoPV requested changes

2025-04-03 17:34 UTC, sharifhsn commented
Closing as I'm no longer actively contributing to hexyl.

2025-04-03 17:34 UTC, closed without merging